FileVersion = 1
Dependencies = {corlib = "*", Pile = "*", Pile_OpenGL = "*", Pile_SDL2 = "*", Pile_SoLoud = "*"}

[Project]
Name = "Game"
TargetType = "BeefGUIApplication"
StartupObject = "Pile.Core"
Aliases = ["PileGame"]
