FileVersion = 1
Dependencies = {corlib = "*", Pile = "*", Pile_OpenGL = "*", Pile_SDL2 = "*", Pile_SoLoud = "*"}

[Project]
Name = "Game"
StartupObject = "Pile.EntryPoint"

# you can just copy these to your own game project file!
[Configs.Debug.Win64]
PostBuildCmds = ["Execute(\"$(BuildDir)/$(ProjectName).exe -packager\")"]

[Configs.Release.Win64]
PostBuildCmds = ["Execute(\"$(BuildDir)/$(ProjectName).exe -packager\")"]
