FileVersion = 1
Projects = {Pile = {Path = "."}, Pile_SoLoud = {Path = "../Implementations/Audio_SoLoud"}, Pile_OpenGL = {Path = "../Implementations/Graphics_OpenGL"}, Pile_bgfx = {Path = "../Implementations/Graphics_bgfx"}, Pile_Null = {Path = "../Implementations/Null"}, Pile_SDL2 = {Path = "../Implementations/System_SDL"}, JSON_Beef = {Path = "../../JSON_Beef/lib"}}

[Workspace]
StartupProject = "Pile"
