FileVersion = 1
Dependencies = {corlib = "*", corlib = "*", JSON_Beef = "*"}

[Project]
Name = "Pile"

[Configs.Debug.Win64]
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"
LibPaths = ["$(ProjectDir)/dist/win64/freetype.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win64/freetype.dll\")"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/win64/freetype.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win64/freetype.dll\")"]

[Configs.Debug.Win32]
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"
LibPaths = ["$(ProjectDir)/dist/win32/freetype.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win32/freetype.dll\")"]

[Configs.Release.Win32]
LibPaths = ["$(ProjectDir)/dist/win32/freetype.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win32/freetype.dll\")"]
