FileVersion = 1
Dependencies = {corlib = "*", MiniZ = "*", "Atma.Json" = "*"}

[Project]
Name = "Pile"

[Configs.Release.Win64]
PostBuildCmds = ["Execute(\"echo \\\"\\\" > $(BuildDir)\\\\output_dir.temp\")"]
