FileVersion = 1
Dependencies = {corlib = "*", corlib = "*", Pile = "*"}

[Project]
Name = "Pile_bgfx"

[Configs.Debug.Win64]
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"
# for Debug we have to specifically state that we want to link with Gdi32.lib for some reason
LibPaths = ["$(ProjectDir)/dist/win64/bxDebug.lib", "$(ProjectDir)/dist/win64/bimgDebug.lib", "$(ProjectDir)/dist/win64/bimg_decodeDebug.lib", "$(ProjectDir)/dist/win64/bgfxDebug.lib", "Gdi32.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/win64/bxRelease.lib", "$(ProjectDir)/dist/win64/bimgRelease.lib", "$(ProjectDir)/dist/win64/bimg_decodeRelease.lib", "$(ProjectDir)/dist/win64/bgfxRelease.lib"]
