FileVersion = 1
Dependencies = {corlib = "*", corlib = "*", Pile = "*"}

[Project]
Name = "Pile_bgfx"

[Configs.Debug.Win64]
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"
LibPaths = ["$(ProjectDir)/dist/win64/bgfx.lib", "$(ProjectDir)/dist/win64/bx.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/win64/bgfx.lib", "$(ProjectDir)/dist/win64/bx.lib"]
