FileVersion = 1
Dependencies = {corlib = "*", corlib = "*", Pile = "*"}

[Project]
Name = "Pile_SDL2"

[Configs.Debug.Win64]
BuildCommandsOnCompile = "IfFilesChanged"
BuildCommandsOnRun = "IfFilesChanged"
LibPaths = ["$(ProjectDir)/dist/win64/SDL2.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win64/SDL2.dll\")"]

[[Configs.Debug.Win64.DistinctOptions]]
Filter = "SDL2.*"
BfOptimizationLevel = "O3"
RuntimeChecks = false
EmitDynamicCastCheck = false
EmitObjectAccessCheck = false

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/win64/SDL2.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/win64/SDL2.dll\")"]

[[Configs.Release.Win64.DistinctOptions]]
Filter = "SDL2.*"
BfOptimizationLevel = "O3"
EmitDebugInfo = "No"
RuntimeChecks = false
EmitDynamicCastCheck = false
EmitObjectAccessCheck = false
